name: machine_backend
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: 1.4.1
  shelf_router: 1.1.4
  drift: 2.18.0
  sqlite3_flutter_libs: 0.5.20

dev_dependencies:
  build_runner: ^2.4.10
  drift_dev: ^2.18.0
